version: "3.9"
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - shipping
  redis:
    image: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
  mysql:
    image: mysql:v1
    container_name: mysql
    
  





networks:
  robo:
    driver: bridge
  