version: "3.9"
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
  redis:
    image: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
networks:
  robo:
    driver: bridge
  