FROM nginx
RUN rm -rf /usr/share/nginx/html/
ADD static /usr/share/nginx/html/
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY default.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]